# Generated by Django 5.2.7 on 2025-10-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_delete_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
    ]
